### ISSUE TITLE
Pivot Plugin expanding non-numeric columns

### ISSUE THREAD

**Issue by nickzoic** [CountESS-Project/CountESS#38]
the Pivot Plugin *can* expand non-numeric columns but the defaults aren't particularly helpful:

![x](https://github.com/CountESS-Project/CountESS/assets/1487686/aee843c3-293f-45cc-97ff-aec1fea5dd5d)
![y](https://github.com/CountESS-Project/CountESS/assets/1487686/512d2d5a-110d-419e-a516-c47ee52605aa)
![z](https://github.com/CountESS-Project/CountESS/assets/1487686/d4ce3561-c136-4a06-94b1-b44e10a0cf37)

* Duplicate values are summed, which for strings means concatenated without separators.
* Fill value is `0`, which for string values is ugly.

[pandas pivot_table](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) can take an `aggfunc` per column, and only a scalar `fill_value` which defaults to NaN.

Possible options:
* Use a friendlier aggfunc on string columns, even if it's just `','.join`
* (this is called to aggregate one or more values, but not *zero* values, so can't provide a custom fill_value)
* Just raise an error/warning if there are index duplicates and a expand column is non-numeric
* Use a null fillvalue but `.fillna(0)` on any columns which were numeric and `.astype(int)` to cast integer columns back to integers (or `.map(lambda x: int(x or 0))`)

**Comment by nickzoic** [comment]
Note that there's a second step here though: in finalize():
``` 
              df = pd.concat(self.dataframes)
              if index_cols:
                  df = df.groupby(by=index_cols, group_keys=True).sum()
```
which [only works with numerics](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.sum.html#pandas.core.groupby.DataFrameGroupBy.sum)
so for now I'm just adding a warning for non-numeric columns.

**Comment by nickzoic** [comment]
Extra issue: when expanding non-numeric columns, we can end up with a mixed dtype column which if you try to sort the tabular view by that column throws an error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/nick/Work/wehi/countess/countess/gui/tabular.py", line 286, in _label_button_1
    self.set_sort_order(num)
  File "/home/nick/Work/wehi/countess/countess/gui/tabular.py", line 274, in set_sort_order
    self.dataframe = self.dataframe.sort_values(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/Work/wehi/countess/.direnv/python-3.11.6/lib/python3.11/site-packages/pandas/core/frame.py", line 6955, in sort_values
    indexer = nargsort(
              ^^^^^^^^^
  File "/home/nick/Work/wehi/countess/.direnv/python-3.11.6/lib/python3.11/site-packages/pandas/core/sorting.py", line 483, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```

(the column in question has values `[0, "four"]`)

**Comment by nickzoic** [comment]
this is fixed now: string values are aggregated by joining with "," and don't get a default 0 even if that's selected.
